"""add document review fields

Revision ID: d69fe003971e
Revises: 25809a1dc361
Create Date: 2026-09-02 18:03:42.146368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd69fe003971e'
down_revision: Union[str, Sequence[str], None] = '25809a1dc361'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('reviewed_by_id', sa.Integer(), nullable=True))
    op.add_column('documents', sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('documents', sa.Column('reject_reason', sa.String(length=500), nullable=True))
    op.add_column(
        'documents',
        sa.Column('vector_done', sa.Boolean(), server_default=sa.false(), nullable=False),
    )
    op.add_column(
        'documents',
        sa.Column('graph_done', sa.Boolean(), server_default=sa.false(), nullable=False),
    )
    op.create_foreign_key(None, 'documents', 'users', ['reviewed_by_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_column('documents', 'graph_done')
    op.drop_column('documents', 'vector_done')
    op.drop_column('documents', 'reject_reason')
    op.drop_column('documents', 'reviewed_at')
    op.drop_column('documents', 'reviewed_by_id')
    # ### end Alembic commands ###
